version: '3'

services:
  nats:
    image: nats
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    labels:
      - "traefik.enable=false"
    volumes:
      - redis-data:/data
  
  messaging-api:
    depends_on:
      - redis
    build:
      context: ./server/messaging/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:messaging-api-latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Redis: redis
    healthcheck:
      disable: true
    labels:
      - "traefik.backend=messaging-api"
      - "traefik.frontend.rule=PathPrefix:/api/messages"
      - "traefik.port=80"

  ranking-api:
    depends_on:
      - nats
      - redis
    build:
      context: ./server/ranking/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:ranking-api-latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Nats: nats://nats:4222
      Redis: redis
    healthcheck:
      disable: true
    labels:
      - "traefik.backend=ranking-api"
      - "traefik.frontend.rule=PathPrefix:/api/ranking"
      - "traefik.port=80"

  voting-api:
    depends_on:
      - nats
      - redis
    build:
      context: ./server/voting/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:voting-api-latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Nats: nats://nats:4222
      Redis: redis
    healthcheck:
      disable: true
    labels:
      - "traefik.backend=voting-api"
      - "traefik.frontend.rule=PathPrefix:/api/votes"
      - "traefik.port=80"

  proxy:
    image: traefik:1.6-alpine
    labels:
      - "traefik.enable=false"
    ports:
      - "9090:80"
      - "9091:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml

volumes:
  redis-data: