version: "3.7"

services:
  nats:
    image: nats

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  messaging-api:
    depends_on:
      - redis
    build:
      context: ./server/messaging/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:messaging-api-latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Redis: redis
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.messaging-api.rule=PathPrefix(`/api/messages`)"
      - "traefik.http.services.messaging-api.loadbalancer.server.port=80"

  ranking-api:
    depends_on:
      - nats
      - redis
    build:
      context: ./server/ranking/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:ranking-api-latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Nats: nats://nats:4222
      Redis: redis
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ranking-api.rule=PathPrefix(`/api/ranking`)"
      - "traefik.http.services.ranking-api.loadbalancer.server.port=80"

  voting-api:
    depends_on:
      - nats
      - redis
    build:
      context: ./server/voting/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:voting-api-latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Nats: nats://nats:4222
      Redis: redis
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voting-api.rule=PathPrefix(`/api/votes`)"
      - "traefik.http.services.voting-api.loadbalancer.server.port=80"

  proxy:
    image: traefik:2.0
    ports:
      - "9090:80"
      - "9091:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

volumes:
  redis-data:
