version: '3'

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    labels:
      - "traefik.enable=false"
    volumes:
      - redis-data:/data
  
  messaging-api:
    build: ./server/messaging/
    image: edsondewes/messaging-api:latest
    environment:
      Redis: redis
    labels:
      - "traefik.backend=messaging-api"
      - "traefik.frontend.rule=PathPrefix:/api/messages"
      - "traefik.port=80"

  voting-api:
    build: ./server/voting/
    image: edsondewes/voting-api:latest
    environment:
      Redis: redis
    labels:
      - "traefik.backend=voting-api"
      - "traefik.frontend.rule=PathPrefix:/api/votes"
      - "traefik.port=80"

  web:
    build:
      context: ./web-clients/react/
      args:
        apiurl: "http://localhost:8080/api"
    image: edsondewes/message-board-react:latest
    labels:
      - "traefik.backend=react-web"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
    
  proxy:
    image: traefik:1.5-alpine
    labels:
      - "traefik.enable=false"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      
volumes:
  redis-data: