version: "3.7"

services:
  nats:
    image: nats

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  messaging-api:
    depends_on:
      - redis
    build:
      context: ./server/messaging/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:messaging-api-latest
    environment:
      Redis: redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.messaging-api.rule=PathPrefix(`/api/messages`)"
      - "traefik.http.services.messaging-api.loadbalancer.server.port=80"

  ranking-api:
    depends_on:
      - nats
      - redis
    build:
      context: ./server/ranking/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:ranking-api-latest
    environment:
      Nats: nats://nats:4222
      Redis: redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ranking-api.rule=PathPrefix(`/api/ranking`)"
      - "traefik.http.services.ranking-api.loadbalancer.server.port=80"

  voting-api:
    depends_on:
      - nats
      - redis
    build:
      context: ./server/voting/
      dockerfile: Api.Dockerfile
    image: edsondewes/message-board:voting-api-latest
    environment:
      Nats: nats://nats:4222
      Redis: redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voting-api.rule=PathPrefix(`/api/votes`)"
      - "traefik.http.services.voting-api.loadbalancer.server.port=80"

  web:
    build: ./web-clients/react/
    image: edsondewes/message-board:web-react-latest
    environment:
      NODE_ENV: production
      INTERNAL_API_URL: http://proxy/api
      PUBLIC_API_URL: http://localhost:8080/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  proxy:
    image: traefik:2.0
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

volumes:
  redis-data:
