version: '3'

services:
  nats:
    image: nats
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    labels:
      - "traefik.enable=false"
    volumes:
      - redis-data:/data
  
  messaging-api:
    depends_on:
      - redis
    build: ./server/messaging/
    image: edsondewes/messaging-api:latest
    environment:
      Redis: redis
    labels:
      - "traefik.backend=messaging-api"
      - "traefik.frontend.rule=PathPrefix:/api/messages"
      - "traefik.port=80"

  ranking-api:
    depends_on:
      - nats
      - redis
    build: ./server/ranking/
    image: edsondewes/ranking-api:latest
    environment:
      Nats: nats://nats:4222
      Redis: redis
    labels:
      - "traefik.backend=ranking-api"
      - "traefik.frontend.rule=PathPrefix:/api/ranking"
      - "traefik.port=80"

  voting-api:
    depends_on:
      - nats
      - redis
    build: ./server/voting/
    image: edsondewes/voting-api:latest
    environment:
      Nats: nats://nats:4222
      Redis: redis
    labels:
      - "traefik.backend=voting-api"
      - "traefik.frontend.rule=PathPrefix:/api/votes"
      - "traefik.port=80"

  web:
    build: ./web-clients/react/
    image: edsondewes/message-board-react:latest
    environment:
      NODE_ENV: production
      INTERNAL_API_URL: http://proxy/api
      PUBLIC_API_URL: http://localhost:8080/api
    labels:
      - "traefik.backend=react-web"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=80"
    
  proxy:
    image: traefik:1.5-alpine
    labels:
      - "traefik.enable=false"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      
volumes:
  redis-data: