// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rankingService.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MessageBoard.Ranking.GRPC {
  public static partial class RankingService
  {
    static readonly string __ServiceName = "MessageBoard.Ranking.GRPC.RankingService";

    static readonly grpc::Marshaller<global::MessageBoard.Ranking.GRPC.ListRequest> __Marshaller_ListRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageBoard.Ranking.GRPC.ListRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageBoard.Ranking.GRPC.RankingResponse> __Marshaller_RankingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageBoard.Ranking.GRPC.RankingResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::MessageBoard.Ranking.GRPC.ListRequest, global::MessageBoard.Ranking.GRPC.RankingResponse> __Method_List = new grpc::Method<global::MessageBoard.Ranking.GRPC.ListRequest, global::MessageBoard.Ranking.GRPC.RankingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "List",
        __Marshaller_ListRequest,
        __Marshaller_RankingResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MessageBoard.Ranking.GRPC.RankingServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RankingService</summary>
    public abstract partial class RankingServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MessageBoard.Ranking.GRPC.RankingResponse> List(global::MessageBoard.Ranking.GRPC.ListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RankingService</summary>
    public partial class RankingServiceClient : grpc::ClientBase<RankingServiceClient>
    {
      /// <summary>Creates a new client for RankingService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RankingServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RankingService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RankingServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RankingServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RankingServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MessageBoard.Ranking.GRPC.RankingResponse List(global::MessageBoard.Ranking.GRPC.ListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return List(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageBoard.Ranking.GRPC.RankingResponse List(global::MessageBoard.Ranking.GRPC.ListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_List, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Ranking.GRPC.RankingResponse> ListAsync(global::MessageBoard.Ranking.GRPC.ListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Ranking.GRPC.RankingResponse> ListAsync(global::MessageBoard.Ranking.GRPC.ListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_List, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RankingServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RankingServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RankingServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_List, serviceImpl.List).Build();
    }

  }
}
#endregion
