// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messageService.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace MessageBoard.Messaging.GRPC {
  public static partial class MessageService
  {
    static readonly string __ServiceName = "MessageBoard.Messaging.GRPC.MessageService";

    static readonly grpc::Marshaller<global::MessageBoard.Messaging.GRPC.CreateRequest> __Marshaller_CreateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageBoard.Messaging.GRPC.CreateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageBoard.Messaging.GRPC.MessageResponse> __Marshaller_MessageResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageBoard.Messaging.GRPC.MessageResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageBoard.Messaging.GRPC.ListRequest> __Marshaller_ListRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageBoard.Messaging.GRPC.ListRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageBoard.Messaging.GRPC.ListResponse> __Marshaller_ListResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageBoard.Messaging.GRPC.ListResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::MessageBoard.Messaging.GRPC.SingleRequest> __Marshaller_SingleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::MessageBoard.Messaging.GRPC.SingleRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::MessageBoard.Messaging.GRPC.CreateRequest, global::MessageBoard.Messaging.GRPC.MessageResponse> __Method_Create = new grpc::Method<global::MessageBoard.Messaging.GRPC.CreateRequest, global::MessageBoard.Messaging.GRPC.MessageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Create",
        __Marshaller_CreateRequest,
        __Marshaller_MessageResponse);

    static readonly grpc::Method<global::MessageBoard.Messaging.GRPC.ListRequest, global::MessageBoard.Messaging.GRPC.ListResponse> __Method_List = new grpc::Method<global::MessageBoard.Messaging.GRPC.ListRequest, global::MessageBoard.Messaging.GRPC.ListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "List",
        __Marshaller_ListRequest,
        __Marshaller_ListResponse);

    static readonly grpc::Method<global::MessageBoard.Messaging.GRPC.SingleRequest, global::MessageBoard.Messaging.GRPC.MessageResponse> __Method_Single = new grpc::Method<global::MessageBoard.Messaging.GRPC.SingleRequest, global::MessageBoard.Messaging.GRPC.MessageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Single",
        __Marshaller_SingleRequest,
        __Marshaller_MessageResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::MessageBoard.Messaging.GRPC.MessageServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MessageService</summary>
    public abstract partial class MessageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::MessageBoard.Messaging.GRPC.MessageResponse> Create(global::MessageBoard.Messaging.GRPC.CreateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MessageBoard.Messaging.GRPC.ListResponse> List(global::MessageBoard.Messaging.GRPC.ListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::MessageBoard.Messaging.GRPC.MessageResponse> Single(global::MessageBoard.Messaging.GRPC.SingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MessageService</summary>
    public partial class MessageServiceClient : grpc::ClientBase<MessageServiceClient>
    {
      /// <summary>Creates a new client for MessageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MessageServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MessageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MessageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MessageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MessageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::MessageBoard.Messaging.GRPC.MessageResponse Create(global::MessageBoard.Messaging.GRPC.CreateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Create(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageBoard.Messaging.GRPC.MessageResponse Create(global::MessageBoard.Messaging.GRPC.CreateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Create, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Messaging.GRPC.MessageResponse> CreateAsync(global::MessageBoard.Messaging.GRPC.CreateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Messaging.GRPC.MessageResponse> CreateAsync(global::MessageBoard.Messaging.GRPC.CreateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Create, null, options, request);
      }
      public virtual global::MessageBoard.Messaging.GRPC.ListResponse List(global::MessageBoard.Messaging.GRPC.ListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return List(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageBoard.Messaging.GRPC.ListResponse List(global::MessageBoard.Messaging.GRPC.ListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_List, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Messaging.GRPC.ListResponse> ListAsync(global::MessageBoard.Messaging.GRPC.ListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Messaging.GRPC.ListResponse> ListAsync(global::MessageBoard.Messaging.GRPC.ListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_List, null, options, request);
      }
      public virtual global::MessageBoard.Messaging.GRPC.MessageResponse Single(global::MessageBoard.Messaging.GRPC.SingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Single(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::MessageBoard.Messaging.GRPC.MessageResponse Single(global::MessageBoard.Messaging.GRPC.SingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Single, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Messaging.GRPC.MessageResponse> SingleAsync(global::MessageBoard.Messaging.GRPC.SingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SingleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::MessageBoard.Messaging.GRPC.MessageResponse> SingleAsync(global::MessageBoard.Messaging.GRPC.SingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Single, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MessageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MessageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MessageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Create, serviceImpl.Create)
          .AddMethod(__Method_List, serviceImpl.List)
          .AddMethod(__Method_Single, serviceImpl.Single).Build();
    }

  }
}
#endregion
